# Set Up

In [95]:
!pip list | grep transformers

sentence-transformers                    5.1.2
transformers                             4.57.2

In [96]:
# This cell will authenticate you and mount your Drive in the Colab.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [97]:
from transformers import AutoTokenizer, AutoModel
import torch
import pandas as pd
import matplotlib.pyplot as plt

# Data Exploration

In [98]:
def pandas_table_column_exploration(df,table_name = ''):
    """
    Given a pandas df, does some initial exploration
    Input:
        df: pandas df to be explored.
        table_name (optional): what you call the pandas df being explored
    """

    print("\n---------------------------------------------------")
    print("Exploring Columns for Table:", table_name)
    print("---------------------------------------------------\n")

    # Grab all the nummeric columns
    num_cols = df.select_dtypes(include='number').columns

    # Print out some basic charecteristics for each column
    for column_name in df.columns:
        print("---------------------------------------------------")
        print("Column:", column_name)
        print("---------------------------------------------------")

        print('dtype:', df[column_name].dtype)
        print('Number of values:', df[column_name].count())
        print('Null count:', df[column_name].isnull().sum())
        print('Number of unique values:', df[column_name].nunique())
        print('Mode:',df[column_name].mode().unique()) #.to_string(index=False)

        if column_name in num_cols:
            print('Max:',df[column_name].max())
            print('Min:',df[column_name].min())


            # make plot
            plt.figure()
            plt.tight_layout()
            plt.boxplot(df[column_name])
            plt.show()

        elif df[column_name].dtype == str:
            print('Average length:',sum(df[column_name].apply(len))/df[column_name].count())

## Perenual Data

In [99]:
perenual_data = pd.read_csv('./drive/MyDrive/DATASCI 266/Project/perenual_data.csv')

In [100]:
perenual_data.head()

,Unnamed: 0,id,common_name,scientific_name,other_name,family,hybrid,authority,subspecies,cultivar,...,default_image.license_name,default_image.license_url,default_image.original_url,default_image.regular_url,default_image.medium_url,default_image.small_url,default_image.thumbnail,pruning_count.amount,pruning_count.interval,default_image
0,0,1,European Silver Fir,['Abies alba'],['Common Silver Fir'],Pinaceae,NaN,NaN,NaN,NaN,...,Attribution-ShareAlike 3.0 Unported (CC BY-SA ...,https://creativecommons.org/licenses/by-sa/3.0...,https://perenual.com/storage/species_image/1_a...,https://perenual.com/storage/species_image/1_a...,https://perenual.com/storage/species_image/1_a...,https://perenual.com/storage/species_image/1_a...,https://perenual.com/storage/species_image/1_a...,NaN,NaN,NaN
1,1,2,Pyramidalis Silver Fir,"[""Abies alba 'Pyramidalis'""]",[],Pinaceae,NaN,NaN,NaN,Pyramidalis,...,Attribution-ShareAlike License,https://creativecommons.org/licenses/by-sa/2.0/,https://perenual.com/storage/species_image/2_a...,https://perenual.com/storage/species_image/2_a...,https://perenual.com/storage/species_image/2_a...,https://perenual.com/storage/species_image/2_a...,https://perenual.com/storage/species_image/2_a...,NaN,NaN,NaN
2,2,3,White Fir,['Abies concolor'],"['Silver Fir', 'Concolor Fir', 'Colorado Fir']",Pinaceae,NaN,NaN,NaN,NaN,...,Attribution-ShareAlike License,https://creativecommons.org/licenses/by-sa/2.0/,https://perenual.com/storage/species_image/3_a...,https://perenual.com/storage/species_image/3_a...,https://perenual.com/storage/species_image/3_a...,https://perenual.com/storage/species_image/3_a...,https://perenual.com/storage/species_image/3_a...,NaN,NaN,NaN
3,3,4,Candicans White Fir,"[""Abies concolor 'Candicans'""]","['Silver Fir', 'Concolor Fir', 'Colorado Fir']",Pinaceae,NaN,NaN,NaN,Candicans,...,Attribution-ShareAlike License,https://creativecommons.org/licenses/by-sa/2.0/,https://perenual.com/storage/species_image/4_a...,https://perenual.com/storage/species_image/4_a...,https://perenual.com/storage/species_image/4_a...,https://perenual.com/storage/species_image/4_a...,https://perenual.com/storage/species_image/4_a...,2.0,yearly,NaN
4,4,5,Fraser Fir,['Abies fraseri'],['Southern Fir'],Pinaceae,NaN,NaN,NaN,NaN,...,Attribution License,https://creativecommons.org/licenses/by/2.0/,https://perenual.com/storage/species_image/5_a...,https://perenual.com/storage/species_image/5_a...,https://perenual.com/storage/species_image/5_a...,https://perenual.com/storage/species_image/5_a...,https://perenual.com/storage/species_image/5_a...,NaN,NaN,NaN

In [101]:

# filter only to thet columns helpful to us
perenual_data = perenual_data[['description',
'plant_anatomy',
'sunlight',
'soil',
'leaf',
'flowers',
'fruits',
'watering',
'cycle',
'origin',
'care_level',
'maintenance',
'growth_rate',
'common_name',
'dimensions',
'attracts',
'drought_tolerant',
'salt_tolerant',
'thorny',
'edible_fruit',
'harvest_season',
'medicinal',
'poisonous_to_humans',
'poisonous_to_pets']]

In [102]:
#perenual_data['drought_tolerant']

In [103]:
pandas_table_column_exploration(perenual_data, 'perenual_data')

---------------------------------------------------
Exploring Columns for Table: perenual_data
---------------------------------------------------

---------------------------------------------------
Column: description
---------------------------------------------------
dtype: object
Number of values: 2990
Null count: 10
Number of unique values: 2990
Mode: ["'Paint The Town Red' is an amazing shade of Dianthus that truly lives up to its name. Its impressive bright pink blooms are far less common than the standard pinks, purples and whites, and it's sure to stand out in almost any landscape. It's an incredibly hardy species, blooming from summer to early autumn, surviving in most soils and requiring little maintenance. Its easy to look after and highly tolerant of a wide range of conditions, making it an excellent choice for gardeners of all levels. The heady sweet scent produced by the blooms will also fill a garden with fragrance, creating a welcoming environment to enjoy."
 'A leek is a member of the Allium ampeloprasum family, and is a vegetable prized for its strong and distinct flavor. It is a versatile plant that has a culinary use in many cuisines around the world, in both raw and cooked forms. Its strong flavor profile makes it popular for soups, salads, mashed potatoes, and other dishes. Its exceptional nutritional value sets it apart from other vegetables, as it is high in various vitamins and minerals such as Vitamin K, Vitamin C and iron. Additionally, leeks contain antioxidants which are beneficial in reducing inflammation and improving overall health. With its amazing flavor and nutritional profile, leeks make an excellent ingredient in a number of dishes; a truly incredible plant.'
 "Abelia 'Edward Goucher' is an amazing plant species, boasting bright variegated foliage, fragrant white flowers, and breathtaking red-purple stems. The leaves of 'Edward Goucher' are green with a creamy yellow edge, making it an eye-catching addition to any garden. During midsummer, the shrub becomes covered in fragrant white flowers that attract bees and hummingbirds. As the season advances, ‘Edward Goucher’s showy stems begin to turn a beautiful red-purple. This Abelia is a great choice for border planting, privacy hedges, and flowering shrubs. It's perfect for creating a standout look for any garden."
 ...
 "Yellowwood (Cladrastis kentukea 'Sweetshade') is an amazing tree for many reasons. It is a deciduous tree with beautiful, fragrant white flowers in the spring. Its flat compound leaves turn yellow in the fall and are an attractive addition to any garden or landscape. Its canopy is full and broad, giving plenty of shade for hot summer days. Its bark is gray-brown and its wood is highly valued in construction, furniture and woodworking. But what makes it truly amazing is its hardiness, surviving in a wide range of climates and soil conditions. It can even withstand drought in some cases! All in all, Yellowwood is a great choice for anyone who wants to add beauty and character to their garden."
 "Yellowwood is an amazing tree species! Its blooms of white and fragrant flowers add to its aesthetic appeal, and the heart-shaped leaves give it an attractive form. It can easily reach heights of 25-40 feet, and its gray bark adds contrast to the vibrant environment it can be found in. Yellowwood is an amazing choice for gardens and yards alike, as its form and foliage provide plenty of shade, as well as gorgeous yellows and oranges in the fall. Plus, it's tolerant of many soil types and can even withstand droughts. All these things make yellowwood an incredible species to enjoy!"
 "‘Beautyberry’ is an extraordinary plant species that never ceases to amaze with its exotic beauty. It is a low-maintenance plant that, once established, will thrive in almost any conditions. The callicarpa dichotoma 'Shiji Murasaki' WINE SPRITZER has stunning deep purple foliage, and its branches are covered in a multitude of delicate, deep purple, eye-catching berries. This combination makes the beautyberry an engaging addition to any garden. It is most-adored for its vibrant colors in autumn and winter months, making a spectacular statement all year round."]
---------------------------------------------------
Column: plant_anatomy
---------------------------------------------------
dtype: object
Number of values: 3000
Null count: 0
Number of unique values: 1461
Mode: ['[]']
---------------------------------------------------
Column: sunlight
---------------------------------------------------
dtype: object
Number of values: 3000
Null count: 0
Number of unique values: 59
Mode: ["['Full sun', 'part shade']"]
---------------------------------------------------
Column: soil
---------------------------------------------------
dtype: object
Number of values: 3000
Null count: 0
Number of unique values: 52
Mode: ['[]']
---------------------------------------------------
Column: leaf
---------------------------------------------------
dtype: bool
Number of values: 3000
Null count: 0
Number of unique values: 2
Mode: [ True]
---------------------------------------------------
Column: flowers
---------------------------------------------------
dtype: bool
Number of values: 3000
Null count: 0
Number of unique values: 2
Mode: [ True]
---------------------------------------------------
Column: fruits
---------------------------------------------------
dtype: bool
Number of values: 3000
Null count: 0
Number of unique values: 2
Mode: [False]
---------------------------------------------------
Column: watering
---------------------------------------------------
dtype: object
Number of values: 3000
Null count: 0
Number of unique values: 3
Mode: ['Average']
---------------------------------------------------
Column: cycle
---------------------------------------------------
dtype: object
Number of values: 2999
Null count: 1
Number of unique values: 4
Mode: ['Perennial']
---------------------------------------------------
Column: origin
---------------------------------------------------
dtype: object
Number of values: 3000
Null count: 0
Number of unique values: 780
Mode: ["['Japan']"]
---------------------------------------------------
Column: care_level
---------------------------------------------------
dtype: object
Number of values: 2508
Null count: 492
Number of unique values: 5
Mode: ['Medium']
---------------------------------------------------
Column: maintenance
---------------------------------------------------
dtype: object
Number of values: 2806
Null count: 194
Number of unique values: 3
Mode: ['Low']
---------------------------------------------------
Column: growth_rate
---------------------------------------------------
dtype: object
Number of values: 2999
Null count: 1
Number of unique values: 4
Mode: ['Low']
---------------------------------------------------
Column: common_name
---------------------------------------------------
dtype: object
Number of values: 3000
Null count: 0
Number of unique values: 1548
Mode: ['coneflower']
---------------------------------------------------
Column: dimensions
---------------------------------------------------
dtype: object
Number of values: 3000
Null count: 0
Number of unique values: 198
Mode: ["[{'type': None, 'min_value': 2, 'max_value': 3, 'unit': 'feet'}]"]
---------------------------------------------------
Column: attracts
---------------------------------------------------
dtype: object
Number of values: 3000
Null count: 0
Number of unique values: 21
Mode: ['[]']
---------------------------------------------------
Column: drought_tolerant
---------------------------------------------------
dtype: bool
Number of values: 3000
Null count: 0
Number of unique values: 2
Mode: [ True]
---------------------------------------------------
Column: salt_tolerant
---------------------------------------------------
dtype: bool
Number of values: 3000
Null count: 0
Number of unique values: 2
Mode: [False]
---------------------------------------------------
Column: thorny
---------------------------------------------------
dtype: bool
Number of values: 3000
Null count: 0
Number of unique values: 2
Mode: [False]
---------------------------------------------------
Column: edible_fruit
---------------------------------------------------
dtype: bool
Number of values: 3000
Null count: 0
Number of unique values: 2
Mode: [False]
---------------------------------------------------
Column: harvest_season
---------------------------------------------------
dtype: object
Number of values: 958
Null count: 2042
Number of unique values: 5
Mode: ['Fall']
---------------------------------------------------
Column: medicinal
---------------------------------------------------
dtype: bool
Number of values: 3000
Null count: 0
Number of unique values: 2
Mode: [False]
---------------------------------------------------
Column: poisonous_to_humans
---------------------------------------------------
dtype: bool
Number of values: 3000
Null count: 0
Number of unique values: 2
Mode: [False]
---------------------------------------------------
Column: poisonous_to_pets
---------------------------------------------------
dtype: bool
Number of values: 3000
Null count: 0
Number of unique values: 2
Mode: [False]

In [109]:
perenual_data.isna().sum().sort_values()

plant_anatomy             0
sunlight                  0
soil                      0
leaf                      0
fruits                    0
flowers                   0
watering                  0
origin                    0
dimensions                0
attracts                  0
common_name               0
medicinal                 0
edible_fruit              0
thorny                    0
salt_tolerant             0
drought_tolerant          0
poisonous_to_pets         0
poisonous_to_humans       0
cycle                     1
growth_rate               1
description              10
maintenance             194
care_level              492
harvest_season         2042
dtype: int64